### PR TITLE
DigitalSource -> DigitalInput

### LINKED ISSUE #8: 2017 wpilib
Will this library be updated to work with the new 2017 wpilib?

### LINKED ISSUE #9: InterruptSource class -
I have tried to use this class with the 2017 control system, and I'm encountering an error that I'm not sure how to solve. 

```
private static class InterruptSource extends DigitalSource {
    public InterruptSource(int channel) {
      initDigitalPort(channel, true);
    }
  }
```

This piece of code is throwing two errors in Eclipse: First it asks to implement several required methods from the interface. Easy enough, though I'm not sure what effect it would have on the code.

The second error is on the `initDigitalPort(` function, which I assume sets the digital input for the interrupt and then enables it. This function seems to be missing from the 2017 WPIlibj implementation of `DigitalSource`. Not only is it missing, but I can't seem to find any mention of any way to set the interrupt pin through `DigitalSource` or any of its parent classes. I feel like this is an oversight, though it would be greatly appreciated if someone could point me in the right direction to fixing this.

### PR DESCRIPTION
**Pull request by AustinShalit**
closes #8 
closes #9 

Caused by: https://github.com/wpilibsuite/allwpilib/commit/3593ecb17e7c12bcf3167eb1dd5532236edb1213

If someone could do the C++ version :)

### CODE REVIEW

**Comment by niwhsa9** [comment]
Ah thank you, this certainly removes the compiler errors. Have you tested this to ensure that it is working as intended? I can't test atm because I'm not with my team's robot.

**Comment by AustinShalit** [comment]
No but it _should_ work the same as before.  If you could test it and let us know that it works that would be great!

**Comment by niwhsa9** [comment]
Ah thank you so much. I'll go give it a shot tomorrow at practice (2:30 PST ) and update you as soon as possible so you can merge. I really appreciate your help. Fair warning though, my team's never used these sensors so we might take a while to figure it out and we really have no benchmark to go off of.

**Review by PeterJohnson — APPROVED** [review]

**Comment by orangelight** [comment]
It seems to work now, thanks!

**Pull request merged**
