### PR TITLE
Updated Java class for 2018 WPILib

### PR DESCRIPTION
**Pull request by calcmogul**
I don't have an Eclipse environment for Java robot programs set up and this
repository's build is broken, so I can't verify this patch builds. Currently,
2017 WPILib is used to build, but I don't know enough about Gradle to update
it.

### CODE REVIEW

**Comment by juchong** [comment]
Hi! I'm actually in the middle of working on a massive update for the driver including C++/Java fixes for Gradle. It should be ready in a few hours!

**Comment by calcmogul** [comment]
Ok, I was wondering about that. Feel free to use this as a reference if desired then close it once the other patch is ready.

**Comment by HeroCC** [comment]
Hey @juchong any update on the new update? This fork doesn't seem to build either: https://jitpack.io/com/github/calcmogul/ADIS16448-RoboRIO-Driver/update-java-2018.1-g043daf0-3/build.log. I made a ticket on #20

**Comment by juchong** [comment]
Just updated a few minutes ago! Give it a try and let me know!

**Comment by juchong** [comment]
Closing this since the issue has been resolved by a re-write of the driver for Java.

**Pull request closed without merging**
