### PR TITLE
Convert to Gradle Multi Module project

### PR DESCRIPTION
**Pull request by HeroCC**
Removed a bunch of build caches that shouldn't be included. Converts the entire project from a mixed gradle / ant / wpilib / eclipse project to a Gradle / GradleRIO built project, with a C++ and Java module. This enables compatibility with maven repos such as JitPack and allows teams to dynamically fetch your project (see https://jitpack.io/#HeroCC/ADIS16448-RoboRIO-Driver and https://jitpack.io/#juchong/ADIS16448-RoboRIO-Driver). I didn't actually change any code here, just a restructure of the build code and some small javadoc tweaks.

### CODE REVIEW

**Comment by juchong** [comment]
Thanks for your contribution!

I agree with the clean-up and conversion to a gradle module, but I need the eclipse plugins and examples to remain with each language. The reason for this is I'm trying to enable as many students as possible to use our sensor and removing all these examples will likely cause more confusion than good. Most people evaluating our sensor for use on a robot will want an "out of the box" program to quickly get started and won't spend time building code around the sensor. 

If you could roll back the removal of the eclipse projects, I'd be happy to merge the pull request.

**Comment by HeroCC** [comment]
I made a new commit with detailed install instructions and examples for Java and C++. 

Right now teams will still need to do a lot of tweaks to get the included examples to work on their robot (ex right now the project files reference [different](https://github.com/juchong/ADIS16448-RoboRIO-Driver/blob/3f8f53333bd87c8735a7a9bcd79104648e10978a/C%2B%2B/build.gradle#L7) [teams](https://github.com/juchong/ADIS16448-RoboRIO-Driver/blob/0c2ce51a32a3b44955bbfe1e46855c608f757f82/Java/build.properties#L2) in a few places, of which the students will need to change). Plus for eclipse, teams will still need to follow the FRC instructions as I think that eclipse won't install plugins automatically from imported projects (I may be wrong though, I don't use eclipse often). Generally I've found it's better to not include IDE files as often they won't have the same environment they expect from when they were made.

If you'd still like a full example I can include an eclipse project, but I feel overall it would be better for teams to install it themselves (the simplest way they can do it is to copy one file [two for c++] into their project). If they are investigating getting this sensor, they will likely already have a project made, as you need a working RoboRIO to even use it.

**Comment by juchong** [comment]
Thanks for the awesome update! I think that the changes should be enough to get a team started, so I've gone ahead and merged. I'm in the process of updating the main documentation more language-agnostic and moving the LabVIEW documentation to it's own folder.

**Comment by HeroCC** [comment]
Thanks for merging, glad to help!

**Pull request merged**
